TS_SEARCH_PATHS=(~/Projects ~/FPT/deployprj ~/personal)
TS_MAX_DEPTH=1
TS_EXTRA_SEARCH_PATHS=(~/dotfiles:0 ~/dotfiles/nvim/dot-config/nvim:0)
# TS_LOG=file

TS_SESSION_COMMANDS=("nvim ." "claude" "lazygit" "htop")
