[Appearance]
color_scheme_path=/usr/share/color-schemes/CatppuccinMacchiatoRed.colors
custom_palette=false
icon_theme=Papirus-Dark
standard_dialogs=default
style=kvantum

[Fonts]
fixed="Monospace,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Sans Serif,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xa4\0\0\x5\x35\0\0\0\0\0\0\0\0\0\0\x4\xa4\0\0\x5\x35\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xa4\0\0\x5\x35)
